name: Exercism Sync and Automerge

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR author and add label
        uses: actions-ecosystem/action-add-labels@v1
        if: github.actor == 'exercism-solutions-syncer[bot]'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge

  auto-merge:
    runs-on: ubuntu-latest
    needs: add-label
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check PR author
        if: github.event.pull_request.user.login == 'exercism-solutions-syncer[bot]'
        run: echo "PR creato da exercism-solutions-syncer[bot] — procedo al merge."

      - id: automerge
        name: Auto merge PR
        if: github.event.pull_request.user.login == 'exercism-solutions-syncer[bot]'
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          LOG_LEVEL: debug
